BEGIN;
DROP TABLE "Shoutbox";
DROP TABLE "KierunkiStudenta";
DROP TABLE "Kierunek";
DROP TABLE "Wydzial";
DROP TABLE "GrupyStudentow";
DROP TABLE "Student";
DROP TABLE "AktualneWydarzenie";
DROP TABLE "NotatkaDoWydarzenia";
DROP TABLE "Kalendarz";
DROP TABLE "Wydarzenie";
DROP TABLE "ZmianaDat";
DROP TABLE "NotatkaDoPlanu";
DROP TABLE "Tydzien";
DROP TABLE "Grupa";
DROP TABLE "Konsultacje";
DROP TABLE "Miejsce";
DROP TABLE "KategoriaMiejsca";
DROP TABLE "Prowadzacy";
DROP TABLE "Kurs";
DROP TABLE "Uzytkownik";
COMMIT;